export const categoryMap = {
  Navigace: "navigace",
  Doprava: "doprava",
  Občerstvení: "obcerstveni",
  Ubytování: "ubytovani",
  "Turistické cíle": "turisticke_cile",
  Ostatní: "ostatni",
};

export const typeMap = {
  Hotel: "hotel",
  Penzion: "penzion",
  "Turistická chata": "turisticka_chata",
  Kemp: "kemp",
  "Nouzové nocoviště": "nouzove_nocoviste",
  "Trail angel": "trail_angel",
  Restaurace: "restaurace",
  Bufet: "bufet",
  Obchod: "obchod",
  Večerka: "vecerka",
  Kavárna: "kavarna",
  Pekárna: "pekarna",
  "Zdroj vody": "zdroj_vody",
  Rozcestník: "rozcestnik",
  Milník: "milnik",
  Mapa: "mapa",
  "Začátek etapy": "zacatek_etapy",
  "Konec etapy": "konec_etapy",
  "Nouzový bod": "nouzovy_bod",
  Uzavírka: "uzavirka",
  "Turistický přístřešek": "turisticky_pristresek",
  Vrchol: "vrchol",
  "Hraniční přechod": "hranicni_prechod",
  Vlak: "vlakova_zastavka",
  Autobus: "autobusova_zastavka",
  Převoz: "prevoz",
  Parkoviště: "parkoviste",
  "Nabíjecí stanice": "nabijeci_stanice",
  Kostel: "kostel",
  Kaple: "chapel",
  "Kulturní památka": "kulturni_pamatka",
  Rozhledna: "rozhledna",
  Vyhlídka: "vyhlidka",
  "Památný strom": "pamatny_strom",
  "Turistické informační centrum": "turisticke_informacni_centrum",
  Muzeum: "muzeum",
  Kříž: "kriz",
  Ostatní: "ostatni",
  Razítko: "razitko",
  Zásilkovna: "zasilkovna",
  Bankomat: "bankomat",
  Obec: "obec",
};
